### ISSUE TITLE
The latest pip package doesn't look like it has been updated with latest changes from master

### ISSUE THREAD

**Issue by inuyasha82** [mrk-andreev/tornado-swagger#82]
I was trying the allow_cors option on the latest version 1.5.0, 

and when trying to start the server having the `allow_cors=True` inside the setup_swagger function, i get the following error:

```
Traceback (most recent call last):
  File "/home/gualandri/Projects/IBM/Agro/test_swagger/src/main.py", line 105, in <module>
    app = Application()
          ^^^^^^^^^^^^^
  File "/home/gualandri/Projects/IBM/Agro/test_swagger/src/main.py", line 86, in __init__
    setup_swagger(self._routes,
TypeError: setup_swagger() got an unexpected keyword argument 'allow_cors'
```

So i tried to look at the sources that are inside my local folder and what the _handlers.py file content is: 

```python
import tornado.web


class TornadoBaseHandler(tornado.web.RequestHandler):
    def data_received(self, chunk: bytes):
        pass


class SwaggerUiHandler(TornadoBaseHandler):
    SWAGGER_HOME_TEMPLATE = ""

    def get(self):
        self.write(self.SWAGGER_HOME_TEMPLATE)


class SwaggerSpecHandler(TornadoBaseHandler):
    SWAGGER_SPEC = ""

    def get(self):
        self.write(self.SWAGGER_SPEC)

```

That apparently is missing all the changes to add the allow-cors option. 

I also tried to download the pip package: https://files.pythonhosted.org/packages/d5/bf/a7040e7ee12aa6d5401c951e94b7b83e8ebbca04e4d538238233dbd79709/tornado-swagger-1.5.0.tar.gz 

And got the same result, and the last modified  date for the files, is:

```sh
total 32
drwxrwxr-x. 1 gualandri gualandri  180 Sep 23 20:35 ./
drwxrwxr-x. 1 gualandri gualandri  216 Sep 23 20:35 ../
-rw-rw-r--. 1 gualandri gualandri 8174 Aug  4  2022 _builders.py
-rw-rw-r--. 1 gualandri gualandri   73 Aug  4  2022 const.py
-rw-rw-r--. 1 gualandri gualandri  403 Aug  4  2022 _handlers.py
-rw-rw-r--. 1 gualandri gualandri   22 Sep 23 20:33 __init__.py
-rw-rw-r--. 1 gualandri gualandri  626 Aug  4  2022 model.py
-rw-rw-r--. 1 gualandri gualandri  665 Aug  4  2022 parameter.py
-rw-rw-r--. 1 gualandri gualandri 2786 Aug  4  2022 setup.py
drwxrwxr-x. 1 gualandri gualandri   14 Sep 23 20:35 swagger_ui/
drwxrwxr-x. 1 gualandri gualandri   24 Sep 23 20:35 templates/
```

I was expecting something closer to september 2023, not last year at least for _handlers.py

**Comment by mrk-andreev** [comment]
Thank you for your help and sorry for late response. 

I fixed that issue in 1.6.0 release 

```
- Add OpenAPI 3.1 support and standards compatibility tests for Swagger 2.0, OpenAPI 3.0.3, and OpenAPI 3.1.0.
- Add swagger_ui_version option to setup_swagger so the Swagger UI release loaded from cdnjs can be parametrized (defaults to 4.13.2).
- Add swagger_ui_css_sri, swagger_ui_bundle_sri and swagger_ui_preset_sri options to supply matching subresource integrity hashes for a custom version (pass empty strings to disable integrity checking).
- Fix allow_cors so CORS headers are also sent on the GET responses (previously only the preflight OPTIONS response carried them, so cross-origin spec fetches still failed in browsers).
- Add cors_origin option to configure Access-Control-Allow-Origin instead of always using *.
- Fix OpenAPI 3 server metadata generation and security scheme placement.
- Add OpenAPI 3 JWT bearer authentication support.
- Fix executable Swagger example endpoint and installation issue.
- Add tox, Ruff linting, mypy checks, and broader test coverage.
-  Improve README and example documentation.
```
